### ISSUE TITLE
A few updates to the readme

### ISSUE THREAD

**Issue by achall36** [oxygenxml/dita-custom-ant-parser#2]
Hi Radu

I got this to work for Asciidoc.

I needed to change the path to the ditabase.dtd in `com.oxygenxml.ant.parser.dita\resources\dbdita\db2dita\docbook2dita.xsl`

I changed
`doctype-system="../../../../dtd/ditabase.dtd"`
to a path that connected for my installation, so I hacked it to `doctype-system="C:/dita-ot-3.5/plugins/org.dita.specialization.dita11/dtd/ditabase.dtd"`

I only wanted to test this for Asciidoc and did not install RST software or bother with any RST configuration. So the RST requirements appear optional.
All I did was comment out the RST file in `com.oxygenxml.ant.parser.dita\samples\samples.ditamap`.

As my team has a lot of DITA and now starts to use Asciidoc, I will plan to test this further.

Best,
Andy Hall
SS&C Algorithmics

**Comment by raducoravu** [comment]
@achall36 you did well commenting out the RST parts, hopefully this plugin will prove useful for you, I did not invest much time into it but maybe based on your feedback we can evolve it. About changing the doctype-system for the DITA composite generation, you shouldn't have bothered, when a DITA composite XML document is edited or published, the public ID is enough to resolve the reference to the DTD.
So the DOCTYPE system ID can point to anything like:

    <!DOCTYPE dita PUBLIC "-//OASIS//DTD DITA Composite//EN" "someNotExisting.dtd">

as long as the public ID is correct, the system ID part will not be used for anything.
I will change the "docbook2dita.xsl" to generate the composite system ID without any of the "../" relative folder paths in it:

     <!DOCTYPE dita PUBLIC "-//OASIS//DTD DITA Composite//EN" "ditabase.dtd">
